#!/usr/bin/env bash
#
# Small tool to quickly calculate center frequency for a given
# channel and width on a specified band.
#
# See lib/wifi-common.sh for the underlying formulas.

source "$(dirname "${BASH_SOURCE[0]}")/lib/wifi-common.sh"

function showHelp() {
  echo "*******************************************************************************"
  echo " $0 lets you compute either the center freq for a given channel or derive"
  echo " the frequency from a provided channel."
  echo "*******************************************************************************"
  echo "Available options:"
  echo "-f <frequency>: Frequency to use to get the control channel."
  echo "-c <channel>: Channel to use to derive the frequency."
  echo "-b <band>: Specify which band to use. Options are 24,5,6."
  echo "-v: Use verbose output"
  echo "-h: Show this help."
  echo ""

}

##############################################################################################################
# Argument processing
##############################################################################################################
verbose='false'
startChannel=''
startFrequency=''
band='24'
while getopts "f:c:b:vh" opt; do
  case "${opt}" in
    c) startChannel="$OPTARG" ;;
    f) startFrequency="$OPTARG" ;;
    b) band="$OPTARG" ;;
    v) verbose='true' ;;
    h) showHelp ;;
    *) err "Invalid option: ${opt}" ;;
  esac
done

clientChannel=''
centerFrequency=''


if [[ -n "$startChannel" ]]; then
  centerFrequency=$(calcCenterFreq "${startChannel}" "${band}")
  # Print out the center frequency
  if [[ "$verbose" == "true" ]]; then
    err "Frequency == $centerFrequency"
  else
    echo "$centerFrequency"
  fi
elif [[ -n "$startFrequency" ]]; then
  clientChannel=$(getChannelFromFrequency "${startFrequency}" "${band}")
  # Print out the client channel
  if [[ "$verbose" == "true" ]]; then
    err "Channel == $clientChannel"
  else
    echo "$clientChannel"
  fi
fi

if [[ "$verbose" == "true" ]]; then
   case "${band}" in
    24) fullBand="2.4GHz" ;;
    5) fullBand="5GHz" ;;
    6) fullBand="6GHz" ;;
    *) err "Invalid Frequency" ;;
  esac
  err "Band == $fullBand"
fi
